### ISSUE TITLE
Extraction of event logs

### ISSUE THREAD

**Issue by christbryan** [process-analytics/bpmn-visualization-R#175] opened 2022-12-29 13:33 UTC
Hello Bonitasoft Team,

I exeucuted my Bonita solution several times and now need to extract the event logs for process analytics. Please could you give a step by step guide on how to do so?

Best Regards

**Comment by tbouffard** [comment] 2022-12-29 14:20
This R package is only for visualizing execution data on BPMN diagrams for the R ecosystem.
It doesn't handle event logs at all.

Duplicate of https://github.com/process-analytics/bpmn-layout-generators/issues/107. We will answer there.
In the future, please don't post the same question in various places. This would be considered as spam.
So closing.

**Closed by tbouffard** 2022-12-29 14:20 UTC
Labels: duplicate, question

**Comment by christbryan** [comment] 2022-12-29 14:27
Okay thanks for the answer.

But I would like to send my event log through the process analytics form
for my event log to be analyzed but don't know how to get my event logs.

Any help will be appreciated please.

Thanks

Le jeu. 29 déc. 2022 à 15:20, Thomas Bouffard ***@***.***> a
écrit :
